engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.js"
